'use client'

import { useState } from 'react'
import { AppNavbar } from '@/components/shared/AppNavbar'
import { AppSidebar } from '@/components/shared/AppSidebar'
import { Copy, Check, FileDown, ArrowLeft } from 'lucide-react'
import Link from 'next/link'
import { useTheme } from '@/lib/theme/ThemeProvider'
import type { Artifact } from '@/types/diagram'

interface ExplainDiagramDetailShellProps {
  email: string
  fullName: string | null
  plan: string
  generationsRemaining: number
  artifact: Artifact
}

function formatTime(d: Date): string {
  return d.toLocaleTimeString('en-US', { hour: '2-digit', minute: '2-digit' })
}

function formatDateLong(d: Date): string {
  return d.toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' }) + ' ' + formatTime(d)
}

function parseSections(text: string) {
  const sections: { title: string; body: string }[] = []
  const titles = ['OVERVIEW', 'KEY COMPONENTS', 'FLOW & PROCESS', 'PURPOSE']
  for (const title of titles) {
    const idx = text.indexOf(title)
    if (idx === -1) continue
    const afterTitle = text.slice(idx + title.length).trimStart()
    const nextIdx = Math.min(
      ...titles.filter(t => t !== title).map(t => {
        const i = text.indexOf(t, idx + title.length)
        return i === -1 ? Infinity : i
      })
    )
    const body = (nextIdx === Infinity ? afterTitle : afterTitle.slice(0, nextIdx - idx - title.length)).trim()
    sections.push({ title, body })
  }
  if (sections.length === 0) sections.push({ title: 'EXPLANATION', body: text.trim() })
  return sections
}

export function ExplainDiagramDetailShell({ email, fullName, plan, generationsRemaining, artifact }: ExplainDiagramDetailShellProps) {
  const { theme } = useTheme()
  const isDark = theme === 'dark'
  const [copied, setCopied] = useState(false)
  const [isExporting, setIsExporting] = useState(false)

  const T = {
    cardBg:          isDark ? 'rgba(255,255,255,0.03)' : '#FFFFFF',
    cardBorder:      isDark ? 'rgba(255,255,255,0.08)' : '#E5E7EB',
    cardHeaderBg:    isDark ? 'rgba(255,255,255,0.04)' : '#F8F9FA',
    cardHeaderBorder:isDark ? 'rgba(255,255,255,0.06)' : '#F3F4F6',
    cardTitleColor:  isDark ? '#F1F5F9'                : '#111827',
    cardMetaColor:   isDark ? '#52525B'                : '#9CA3AF',
    sectionTitle:    isDark ? '#94A3B8'                : '#6B7280',
    bodyText:        isDark ? '#CBD5E1'                : '#374151',
    divider:         isDark ? 'rgba(255,255,255,0.06)' : '#F3F4F6',
    actionBg:        isDark ? 'rgba(255,255,255,0.05)' : 'rgba(0,0,0,0.04)',
    actionBorder:    isDark ? 'rgba(255,255,255,0.08)' : '#E5E7EB',
    actionColor:     isDark ? '#94A3B8'                : '#374151',
    rightBg:         isDark ? 'rgba(255,255,255,0.02)' : '#F8FAFF',
  }

  const content = artifact.content as { explanation?: string; fileName?: string; createdAt?: string } | null
  const explanation = content?.explanation ?? ''
  const fileName = artifact.title
  const createdAt = content?.createdAt ? new Date(content.createdAt) : new Date(artifact.created_at)
  const sections = parseSections(explanation)

  const handleCopy = () => {
    navigator.clipboard.writeText(explanation)
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  const handleExportPDF = async () => {
    if (isExporting) return
    setIsExporting(true)
    try {
      const [{ default: jsPDF }, { default: html2canvas }] = await Promise.all([
        import('jspdf'),
        import('html2canvas'),
      ])

      const container = document.createElement('div')
      container.style.cssText = [
        'position:fixed', 'top:-9999px', 'left:-9999px',
        'width:794px', 'background:#ffffff',
        'font-family:Georgia,serif', 'color:#111827',
        'padding:64px 56px', 'box-sizing:border-box',
      ].join(';')

      const dateStr = formatDateLong(createdAt)
      const escapeHtml = (s: string) => s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/\n/g, '<br>')

      container.innerHTML = `
        <div style="border-bottom:2px solid #6366F1;padding-bottom:20px;margin-bottom:36px;">
          <div style="font-family:Inter,sans-serif;font-size:10px;font-weight:700;letter-spacing:0.12em;text-transform:uppercase;color:#6366F1;margin-bottom:10px;">Diagram Explanation</div>
          <div style="font-size:22px;font-weight:700;color:#111827;margin-bottom:6px;">${escapeHtml(fileName)}</div>
          <div style="font-size:12px;color:#6B7280;font-family:Inter,sans-serif;">Generated by Flowmapr · ${escapeHtml(dateStr)}</div>
        </div>
        ${sections.map(s => `
          <div style="margin-bottom:32px;">
            <div style="font-family:Inter,sans-serif;font-size:10px;font-weight:700;letter-spacing:0.12em;text-transform:uppercase;color:#6366F1;margin-bottom:12px;">${escapeHtml(s.title)}</div>
            <div style="font-size:14px;line-height:1.8;color:#374151;">${escapeHtml(s.body)}</div>
          </div>
        `).join('')}
        <div style="margin-top:56px;padding-top:16px;border-top:1px solid #E5E7EB;font-family:Inter,sans-serif;font-size:11px;color:#9CA3AF;text-align:center;">flowmapr.com</div>
      `

      document.body.appendChild(container)

      const canvas = await html2canvas(container, {
        scale: 2,
        useCORS: true,
        backgroundColor: '#ffffff',
        width: 794,
        windowWidth: 794,
      })

      document.body.removeChild(container)

      const imgData = canvas.toDataURL('image/png')
      const pdf = new jsPDF({ orientation: 'portrait', unit: 'px', format: 'a4' })
      const pdfWidth = pdf.internal.pageSize.getWidth()
      const pdfHeight = pdf.internal.pageSize.getHeight()
      const scaledHeight = (canvas.height / 2) * (pdfWidth / (canvas.width / 2))

      if (scaledHeight <= pdfHeight) {
        pdf.addImage(imgData, 'PNG', 0, 0, pdfWidth, scaledHeight)
      } else {
        let yOffset = 0
        let remaining = scaledHeight
        while (remaining > 0) {
          pdf.addImage(imgData, 'PNG', 0, -yOffset, pdfWidth, scaledHeight)
          remaining -= pdfHeight
          yOffset += pdfHeight
          if (remaining > 0) pdf.addPage()
        }
      }

      const safeName = fileName.replace(/\.[^.]+$/, '').replace(/[^a-z0-9]/gi, '-')
      pdf.save(`${safeName}-explanation.pdf`)
    } catch (err) {
      console.error('[exportPDF]', err)
    } finally {
      setIsExporting(false)
    }
  }

  return (
    <div className="flex h-screen flex-col bg-[var(--color-bg)]">
      <AppNavbar email={email} fullName={fullName} generationsRemaining={generationsRemaining} />
      <div className="flex flex-1 overflow-hidden">
        <AppSidebar plan={plan} />

        <main className="flex flex-1 flex-col overflow-auto">
          <div className="p-6" style={{ maxWidth: 860 }}>
            {/* Back nav */}
            <Link href="/workspace" style={{ display: 'inline-flex', alignItems: 'center', gap: 6, fontSize: 13, color: isDark ? '#64748B' : '#9CA3AF', textDecoration: 'none', marginBottom: 20, fontFamily: 'Inter, sans-serif' }}>
              <ArrowLeft size={14} /> Back to workspace
            </Link>

            {/* Result card */}
            <div style={{ borderRadius: 12, background: T.cardBg, border: `1px solid ${T.cardBorder}`, overflow: 'hidden' }}>
              {/* Header */}
              <div style={{ padding: '16px 20px', background: T.cardHeaderBg, borderBottom: `1px solid ${T.cardHeaderBorder}` }}>
                <div style={{ fontSize: 14, fontWeight: 700, color: T.cardTitleColor, fontFamily: 'Inter, sans-serif' }}>
                  Diagram Explanation
                </div>
                <div style={{ fontSize: 11, color: T.cardMetaColor, fontFamily: 'Inter, sans-serif', marginTop: 3 }}>
                  {fileName} · {formatTime(createdAt)}
                </div>
              </div>

              {/* Sections */}
              <div style={{ padding: '20px' }}>
                {sections.map((section, i) => (
                  <div key={i} style={{ marginBottom: i < sections.length - 1 ? 20 : 0 }}>
                    <div style={{ fontSize: 10, fontWeight: 700, color: T.sectionTitle, letterSpacing: '0.1em', textTransform: 'uppercase', fontFamily: 'Inter, sans-serif', marginBottom: 6 }}>
                      {section.title}
                    </div>
                    <div style={{ fontSize: 13, color: T.bodyText, lineHeight: 1.75, fontFamily: 'Inter, sans-serif' }}>
                      {section.body}
                    </div>
                    {i < sections.length - 1 && <div style={{ height: 1, background: T.divider, marginTop: 20 }} />}
                  </div>
                ))}
              </div>

              {/* Footer */}
              <div style={{ padding: '14px 20px', borderTop: `1px solid ${T.cardHeaderBorder}`, display: 'flex', gap: 8, flexWrap: 'wrap' }}>
                <button onClick={handleCopy} style={{
                  flex: 1, minWidth: 130, padding: '9px 14px', borderRadius: 8,
                  border: `1px solid ${copied ? 'rgba(34,197,94,0.3)' : T.actionBorder}`,
                  background: copied ? 'rgba(34,197,94,0.08)' : T.actionBg,
                  color: copied ? '#4ADE80' : T.actionColor,
                  fontSize: 12, fontWeight: 500, fontFamily: 'Inter, sans-serif',
                  cursor: 'pointer', transition: 'all 0.15s ease',
                  display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 6,
                }}>
                  {copied ? <Check size={12} /> : <Copy size={12} />}
                  {copied ? 'Copied!' : 'Copy explanation'}
                </button>
                <button onClick={handleExportPDF} disabled={isExporting} style={{
                  flex: 1, minWidth: 130, padding: '9px 14px', borderRadius: 8,
                  border: `1px solid ${T.actionBorder}`, background: T.actionBg, color: T.actionColor,
                  fontSize: 12, fontWeight: 500, fontFamily: 'Inter, sans-serif',
                  cursor: isExporting ? 'not-allowed' : 'pointer',
                  opacity: isExporting ? 0.7 : 1,
                  display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 6,
                }}>
                  <FileDown size={12} /> {isExporting ? 'Exporting…' : 'Export as PDF'}
                </button>
              </div>
            </div>
          </div>
        </main>
      </div>

    </div>
  )
}
