interface ApiEndpoint {
  id: string
  method: string
  path: string
  summary: string
  description?: string
  tags?: string[]
  parameters?: Array<{
    name: string
    in: string
    required: boolean
    type: string
    description?: string
  }>
  requestBody?: { contentType: string; schema: string } | null
  responses?: Array<{ status: number; description: string; schema?: string | null }>
}

interface ApiService {
  id: string
  name: string
  kind?: string
  technology?: string | null
  endpoints: ApiEndpoint[]
}

const METHOD_BADGE: Record<string, string> = {
  GET: '🟢',
  POST: '🔵',
  PUT: '🟡',
  PATCH: '🟠',
  DELETE: '🔴',
  OPTIONS: '⚪',
  HEAD: '⚫',
}

export function exportMarkdown(services: ApiService[], title = 'API Documentation'): string {
  const lines: string[] = []

  lines.push(`# ${title}`, '')
  lines.push(`> Generated by [Flowmapr](https://app.flowmapr.com)`, '')
  lines.push('---', '')

  for (const svc of services) {
    lines.push(`## ${svc.name}`)
    if (svc.technology) lines.push(`*${svc.technology}*`)
    lines.push('')

    if (svc.endpoints.length === 0) {
      lines.push('_No endpoints_', '')
      continue
    }

    for (const ep of svc.endpoints) {
      const badge = METHOD_BADGE[ep.method] ?? '⚪'
      lines.push(`### ${badge} \`${ep.method}\` ${ep.path}`)
      lines.push('')
      if (ep.summary) lines.push(`**${ep.summary}**`, '')
      if (ep.description) lines.push(ep.description, '')

      if (ep.parameters && ep.parameters.length > 0) {
        lines.push('**Parameters:**')
        lines.push('')
        lines.push('| Name | In | Type | Required | Description |')
        lines.push('|------|-----|------|----------|-------------|')
        for (const p of ep.parameters) {
          lines.push(`| \`${p.name}\` | ${p.in} | ${p.type} | ${p.required ? '✅' : '—'} | ${p.description ?? ''} |`)
        }
        lines.push('')
      }

      if (ep.requestBody) {
        lines.push('**Request Body:**')
        lines.push(`\`Content-Type: ${ep.requestBody.contentType}\``)
        lines.push('```json')
        lines.push(ep.requestBody.schema)
        lines.push('```')
        lines.push('')
      }

      if (ep.responses && ep.responses.length > 0) {
        lines.push('**Responses:**')
        lines.push('')
        for (const resp of ep.responses) {
          lines.push(`- **${resp.status}** — ${resp.description}`)
          if (resp.schema) {
            lines.push('  ```json')
            lines.push(`  ${resp.schema}`)
            lines.push('  ```')
          }
        }
        lines.push('')
      }

      lines.push('---', '')
    }
  }

  return lines.join('\n')
}

export function downloadMarkdown(services: ApiService[], title = 'API Documentation') {
  const md = exportMarkdown(services, title)
  const blob = new Blob([md], { type: 'text/markdown' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = 'api-docs.md'
  a.click()
  URL.revokeObjectURL(url)
}
